### ISSUE TITLE
SEO supporting more search engines

### ISSUE THREAD

**Issue by miss85246** [sanic-org/sanic-guide#103]
Now, we supported google SEO, we can search sanic documentation easily from google with any documentation supported language
![image](https://user-images.githubusercontent.com/42527535/153015536-10fd565f-13fc-435b-ac5d-e693deb5fd33.png)

![image](https://user-images.githubusercontent.com/42527535/153016029-7c9d9da8-9c4a-49f7-bbd5-590d5ea94a5e.png)

![image](https://user-images.githubusercontent.com/42527535/153016163-4d11f3c7-8561-41a3-8555-96f2da22adfe.png)

But out of google，we can't search this documentation. for example， I can't search any offical information in the bigest Chinese search engine —— Baidu.

I think we need let our documentation supported more different countries search engines.

But considering the particularity of Chinese network environment，If you want any supported，you can contact me or Lu，we are willing to provide all help.

:see_no_evil:

**Comment by miss85246** [comment]
Step 1: Register Baidu account.
Step 2: Open Baidu search resource platform.
Step 3: Add site information
In this step, you need to enter the domain name, tell Baidu which category your website belongs to and verify the domain name through CNAME.
Step 4: Add meta in config.js, example: 
```
["meta", { name: "baidu-site-verification", content: "****************" }],
```

**Comment by ahopkins** [comment]
Did you add this @miss85246 ?
