### ISSUE TITLE
invalid contribution guidelines link

### ISSUE THREAD

**Issue by ZinkLu** [sanic-org/sanic-guide#16]
`https://sanic.readthedocs.io/en/latest/sanic/contributing.html`  is now on 404 which still in `guide/README.md`.

do we have a valid contribution guidelines page? or should we link contributing to SCOPE page?

**Comment by ahopkins** [comment]
https://github.com/sanic-org/sanic/blob/master/CONTRIBUTING.rst

Let's link to this for now until we build a new page for it.

**Comment by ZinkLu** [comment]
done. 
see: https://github.com/sanic-org/sanic-guide/commit/501fccc9529197fb2f5fa59f65fc156943186e67#diff-4c87b46cf4cc590f5dfd5b3974a72f4f3c91abf6af253cd85a4bd42463196e63R63
