### ISSUE TITLE
`handlers` in chinese

### ISSUE THREAD

**Issue by ZinkLu** [sanic-org/sanic-guide#17]
在中文中，最古老的翻译是句柄，我看我俩翻译的不太一样，你这边是`响应程序`，我这边是`处理函数`，我突然觉得`响应函数`似乎更加得适合，不知道你怎么看？ @miss85246

**Comment by miss85246** [comment]
我觉得可以，那我们就都叫 `响应函数` 好了。另外，昨晚我仔细的考虑了一下。我觉得除了翻译名词的统一之外，我们还有下面的内容可以确定一下：
1. 所有的中文文档的标题，都带上原有的英文标题，而且括号统一使用英文括号。
2. 所有的翻译中，英文单词、数字前后都应该和中文空出一个空格的位置。（如果连接的是标点符号，则忽略）
3. 除markdown语法、代码中、专用的符号例如$ 、vuepress语法之外的所有的标点符号都应该使用中文符号。
4. 对于 markdown 中的引用、链接、图片、加粗、斜体等特殊格式，也应该在前后添加空格。
5. 文档应尽量遵循 markdown 文档规范，不同的段落、标题与正文内容、以及其他类似的内容应保证前后一行的空行。

翻译内容的话，我们是不是等这次翻译完成之后专门建立一个字典库， 将我们认为重要的名词添加进去，以方便以后文档变动、新的贡献者加入参考。

**Comment by ahopkins** [comment]
我希望我会中文

**Comment by ZinkLu** [comment]
针对你的问题
1. 现在还剩多少标题没有加？没级的标题都要加嘛？
2. 与中文空出一格的是出于什么考虑？阅读感官嘛？
3. 我应该是基本上正文都使用了中文标点，可能有部分遗漏的？这块不知道是不是要从头检查一遍？
4. 同2
5. 关于Markdown规范，我其实不太清除，貌似很多平台都有自己的规范，没有类似pep8之类的官方指导，这块的我们可以单独开一个issue来提这个事情。

一个字典库是有必要的，但是我想知道有什么好的平台嘛？

**Comment by miss85246** [comment]
@ZinkLu 
1. 标题的话，只有一些早期的翻译文件没有加，在我们第一次协商之后，所有的标题都已经加上了英文标题。
2. 空出一格为了阅读感官，看起来更美观，更干净。
3. 检查的事情我来做就好了，这个周末我都有空。
4. 我在 [marklink #18 ](https://github.com/sanic-org/sanic-guide/issues/18#issuecomment-797220599) 中已经进行了详细说明，我认为我们可以将简单的 Markdown 规范上升到文档的书写规范，这有助于：
- 所有文档都以一致的格式显示。
- 为文档创建者提供写作规范。
- 避免翻译人员不必要的工作。
- 成为新的贡献者提供指导。
- 为新语言的翻译人员提供参考。

字典库有必要，但是我目前也没什么想法，google 了一下，感觉都不太合适，这个点我们还需要再讨论一下，但是不着急。
