### ISSUE TITLE
getting-started.md 文件中 sanic.py 应该改为 server.py

### ISSUE THREAD

**Issue by luolitao** [sanic-org/sanic-guide#30]
在
“https://github.com/sanic-org/sanic-guide/blob/main/src/zh/guide/getting-started.md#%E8%BF%90%E8%A1%8Crunning”
处的
“让我们将上面写好的文件保存为 sanic.py， 然后运行它。”
应该改为
“让我们将上面写好的文件保存为 server.py， 然后运行它。”

**Comment by ZinkLu** [comment]
感谢指正，已经修复
Thanks, fixed!
