### ISSUE TITLE
The duplications of the sections after the lists

### ISSUE THREAD

**Issue by ProgramRipper** [sanic-org/sanic-guide#49]
#47  #48 
The same phenomenon appears on "class-based-views" page too. Similarly, both en and zh.😂
相同的现象又出现在“基于类的视图(Class Based Views)”这个页面上了。同样的，中英文界面都有。
![image](https://user-images.githubusercontent.com/45716046/120410017-c3064700-c384-11eb-93ba-d051ac40c876.png)
This time I have looked through the whole document, though I didn't find out any more, please review elsewhere in the document in case of my omission.
这次我已经概览了整个文档，虽然我没有找到更多这样的情况，但是为了以防我的遗漏，请审查一下文档的其他地方。

**Comment by ahopkins** [comment]
Thanks @ProgramRipper.

**Comment by ahopkins** [comment]
Proposed additional line of filler text between list and column sections:

> Let's take a look at our options.
