### ISSUE TITLE
Detail discussion

### ISSUE THREAD

**Issue by miss85246** [sanic-org/sanic-guide#5]
hi, @ahopkins . 
When I translated the chapter of `listener`, [The life cycle of a worker process](https://sanicframework.org/guide/basics/listeners.html) looks not very intuitive.
Have you ever tried to express this concept by using flow chart or other forms? 
I think the flow chart is simpler and more intuitive than the text description, and it will also increase the interest. 
what do you think?

**Comment by ahopkins** [comment]
I don't disagree. It is on my list to do to get [mermaid](https://mermaid-js.github.io/mermaid/#/) integrated with [vuepress](https://github.com/eFrane/vuepress-plugin-mermaidjs).

If you have the time and effort for it now, feel free to add a separate PR for it.

**Comment by miss85246** [comment]
Ok I will depend on the situation
